/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package vub.ig;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int amarok_back=0x7f020000;
        public static final int amarok_next=0x7f020001;
        public static final int amarok_pause=0x7f020002;
        public static final int amarok_play=0x7f020003;
        public static final int amarok_playlist_clear=0x7f020004;
        public static final int amarok_playlist_refresh=0x7f020005;
        public static final int amarok_random=0x7f020006;
        public static final int audio_volume_high=0x7f020007;
        public static final int audio_volume_low=0x7f020008;
        public static final int audio_volume_muted=0x7f020009;
        public static final int icon=0x7f02000a;
    }
    public static final class id {
        public static final int ButtonClear=0x7f050005;
        public static final int ButtonIncreaseVolume=0x7f050009;
        public static final int ButtonLowerVolume=0x7f050007;
        public static final int ButtonMute=0x7f050008;
        public static final int ButtonNext=0x7f050004;
        public static final int ButtonPause=0x7f050003;
        public static final int ButtonRefresh=0x7f050002;
        public static final int ButtonShuffle=0x7f05000a;
        public static final int ListViewSongs=0x7f05000b;
        public static final int TableLayout01=0x7f050000;
        public static final int TableRow01=0x7f050001;
        public static final int TableRow02=0x7f050006;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
